spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:~/taskdbscrum
spring.datasource.username=gihyo
spring.datasource.password=gihyodb

# Spring Boot 2.7で廃止されてspring.sql.init.modeになりました
# spring.datasource.initialization-mode=always
spring.sql.init.mode=always

spring.h2.console.enabled=true

logging.level.org.springframework.security.web=DEBUG

server.servlet.session.timeout=30m

server.servlet.session.cookie.max-age=-1